# Generated by Django 2.2.5 on 2019-09-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartInv', '0002_item_catergory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
