# Generated by Django 2.2.5 on 2019-09-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartInv', '0003_auto_20190907_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='catergory',
        ),
    ]
